#if !canImport(ObjectiveC)
import XCTest

extension EnumPropertiesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnumPropertiesTests = [
        ("testExample", testExample),
        ("testNoAssociatedValues", testNoAssociatedValues),
        ("testRewriteEscaped", testRewriteEscaped),
        ("testRewriteExisting", testRewriteExisting),
        ("testRewriteNesting", testRewriteNesting),
        ("testSingleAssociatedValue", testSingleAssociatedValue),
        ("testSingleDecl", testSingleDecl),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EnumPropertiesTests.__allTests__EnumPropertiesTests),
    ]
}
#endif
